[package]
name = "catr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33" # 乱数生成用

[dev-dependencies]
assert_cmd = "2"
predicates = "2"
rand = "0.8"
